$(document).ready(function(){wrap_DmVideoVm()});function wrap_DmVideoVm(){DmVideoVm.startMethod()}
var DmVideoVm=function(b){b.startMethod=function(){"qs"==cdDaType?(DmVideoGl.bindScroll(function(){b.startClSinGroup(groupArr[splitPageDqNumAjax-1])}),b.startMethodByQs()):"inp"==cdDaType&&(DmVideoGl.bindScroll(function(){DmVideoGlInp.startLoadMyListViHiInp()}),DmVideoGlInp.doMethodByHiInp())};b.startMethodByQs=function(){var a=getQsArr().pa,a=a&&a.split("Hyu");b.startMethodByDataArr(a)};b.startMethodByDataArr=function(a){if(a&&0<a.length){var c=a.length;groupArr=DmVideoGl.getSplitArrs(a,splitPageMyNumAjax);
splitPageZjNumAjax=c;splitPageZyNumAjax=groupArr.length;groupArr&&0<groupArr.length&&b.startClSinGroup(groupArr[0])}};b.startClSinGroup=function(a){var c=a.length;if("qs"==cdDaType)for(var d=0;d<c;d++){var e=$.trim(a[d]);b.startClSinVideo(d,c,e)}else for(d=0;d<c;d++){var f=a[d],g=$.trim(f.id),h=$.trim(f.viMs),e=$.trim(f.viZzUrl),k=$.trim(f.viTitle),f=$.trim(f.imagePath);b.startClSinVideo(d,c,e,g,k,h,f)}};b.startClSinVideo=function(a,c,d,e,f,g,h,k){g=browser.platform.mobile;c=DmVideoGl.getCleanUrl(d);
f=Storage.getItem(c+"_poster");k=Storage.getItem(c+"_viHeight");c=videoWi?videoWi:g?b.getMobileViWiSec():320;c="width:"+(-1!=(c+"").indexOf("%")?c+";":c+"px;");g=videoHi?videoHi:g?b.getMobileViHiSec(k):492;g="height:"+(-1!=(g+"").indexOf("%")?g+";":g+"px;");k="";h=f?f:h;f="lx_"+(cuPrHyUserViLxId+"").replace("-","fu");a=f+"_video"+(a+splitPageMyNumAjax*(splitPageDqNumAjax-1));k=k+(' <video lx-id-sec="'+f+'" vi-id="'+e+'" id="'+a+'" style="'+c+g+'" class="" playsinline  loop controls>\n')+('  <source src="'+
d+'" type="video/mp4" />\n');k+=" </video>\n";DmVideoGl.getVisibleMainCon().append(k);e=$("#"+a);c=e.mediaelementplayer({poster:h,playText:"\u70b9\u51fb\u8fdb\u884c\u64ad\u653e",iceFullScreenMod:"wefs",pauseOtherPlayers:!1,success:function(a){var c=$(a).find("video"),d=c.attr("vi-id"),b=c.attr("lx-id-sec"),c=$(a).parents(".mejs__container"),e=.4*c.width(),b="viEditDiv_"+b+"_"+d;c.append('<div class="viEditDiv" id="'+b+'" data-id="'+d+'"><input type="button" class="editBtn ctrlBtn" style="max-width:'+
e+'px;" value="\u7f16\u8f91"><input type="button" class="delBtn ctrlBtn" style="max-width:'+e+'px;" value="\u5220\u9664"></div>\n');c.addClass("viEditCon");DmVideoGlInp.bindClickSinVideoEdit($("#"+b));DmVideoGlInp.bindClickSinVideoDelete($("#"+b));a.addEventListener("loadeddata",function(a){},!1);a.addEventListener("play",function(a){var c=a.target,d=$(c).find("video");a=d.attr("vi-id");$(d).attr("autobuffer","autobuffer");if(a&&"undefined"!=a){var b=1*a,d=mapViCanPlay.get(b);(b=mapViTimeUpdate.get(b))&&
b.stTime&&(b.stTime=new Date);void 0!=d?d.isSuccess||(c.pause(),alertVipLiSmPop("\u7acb\u5373\u5145\u503c",d.msg)):DmVideoGlInp.ckIsCanPlay(a,function(a){var d=a.isSuccess;mapViCanPlay.put(a.prHyUserViId,{msg:a.messageContent,isSuccess:d});d||(c.pause(),"mustCz"==a.messageCode&&alertVipLiSmPop("\u7acb\u5373\u5145\u503c",a.messageContent))},function(){})}},!1);a.addEventListener("timeupdate",function(a){var c=$(a.target).find("video");a=1*c.attr("vi-id");c=c[0].currentTime;if(mapViTimeUpdate.get(a)){var d=
mapViTimeUpdate.get(a),b=d.stPlTime;10<calcDateChaSeconds(d.stTime,new Date)&&c!=b&&!isAddingPlViRecord&&!d.isRqAddedRecord&&(isAddingPlViRecord=!0,DmVideoGlInp.addHyPlayViRecord(a,function(a){isAddingPlViRecord=!1;var c=a.isSuccess,d=mapViTimeUpdate.get(a.prHyUserViId);d.isRqAddedRecord||(d.isRqAddedRecord=!0);c||console.error(a.messageContent)},function(a,c){isAddingPlViRecord=!1;var d=mapViTimeUpdate.get(c);d.isRqAddedRecord||(d.isRqAddedRecord=!0)}))}else mapViTimeUpdate.put(a,{stTime:new Date,
stPlTime:c,isRqAddedRecord:!1})},!1)}});if(!h)if(browser.platform.mobile)if(browser.platform.iPhone)if(h=mapLoadUrls.size(),f=mapLoadUrls.get(a),"qs"==cdDaType)16>h&&!f&&(c.load(),mapLoadUrls.put(a,d));else{if(cdDaType="inp",3>h&&!f)c.load(),mapLoadUrls.put(a,d)}else c.load(),mapLoadUrls.put(a,d);else c.load(),mapLoadUrls.put(a,d);return e};b.getMobileViWiSec=function(){if(browser.platform.mobile)return"100%"};b.getMobileViHiSec=function(a){if(browser.platform.mobile)return a?a:$(window).height()/
3};b.bindReadyEvent=function(){if(browser.platform.mobile){var a=$("video").not(".loaded"),c=DmVideoGl.getRandomNum(0,a.length-1),a=$(a[c]);(c=a[0].videoHeight)&&0<c&&(a.addClass("loaded"),b.dealCuPageVideoProps(a));0==$("video").not(".loaded").length?window.clearTimeout(bindReadyEventJb):bindReadyEventJb=setTimeout(b.bindReadyEvent,200)}};b.dealCuPageVideoProps=function(a){browser.platform.mobile&&(a=a[0],Storage.getItem(a.currentSrc+"_poster")||DmVideoGl.startDrawCvsImage(a,function(a,d){if(d){var b=
d.src;b&&b.startWith("data:image/png")&&DmVideoGl.getCleanUrl(a.currentSrc)}}))};return b}(window.DmVideoVm||{}),DmVideoGl=function(b){b.getVideoWi=function(){var a="",c=$("#pa_videoWi");c&&0<c.length&&(a=1*c.val());return a};b.getVideoHi=function(){var a="",c=$("#pa_videoHi");c&&0<c.length&&(a=1*c.val());return a};b.getCdDaType=function(){var a="qs",c=$("#pa_cdDaType");c&&0<c.length&&(a=c.val());return a};b.getDzBoLoadHi=function(){var a=0,c=$("#loadMore").height();c&&0<c.length&&(a=1*c.val());return a};
b.getSplitPageMyNumAjax=function(){var a=0,a="qs"==b.getCdDaType()?16:browser.platform.mobile?5:12,c=$("#pa_splMyNum");c&&0<c.length&&(a=1*c.val());return a};b.startDrawCvsImage=function(a,c){var d=document.createElement("canvas"),e=d.getContext("2d");d.width=a.videoWidth;d.height=a.videoHeight;a.crossOrigin="*";e.drawImage(a,0,0,d.width,d.height);e=b.getCanvasImage(d);b.dbScaleTarWiHi(d.width,d.height,$(a).width(),e);c&&c(a,e)};b.dbScaleTarWiHi=function(a,c,d,b){a>c?(b.width=d,b.height=d*c/a):(b.width=
d*a/c,b.height=d)};b.getCanvasImage=function(a){var c=document.createElement("img");c.crossOrigin="*";c.src=a.toDataURL("image/png");return c};b.captureCanvas=function(a,c){html2canvas(a,{onrendered:function(a){c&&c(a)}})};b.getSplitArrs=function(a,c){for(var d=0,d=0,b=1*c,f=[],d=a.length,d=Math.floor((d+b-1)/b),g=0;g<d;g++){for(var h=[],k=0;k<b&&0!=a.length;k++)h.push(a[0]),a.splice(0,1);f.push(h)}return f};b.getCleanUrl=function(a){var c="";return c=-1!=a.indexOf("?")?a.substring(0,a.indexOf("?")):
a};b.bindScroll=function(a){$(window).scroll(function(){if(splitPageDqNumAjax>splitPageZyNumAjax)$(".loadMore").height(0);else if(DmVideoGlInp.isCanSeMyViList("ckScroll")){var c=$(window).scrollTop(),d=$(window).height();b.getVisibleMainConHi()-c-d<=dzBoLoadHi&&a&&a()}})};b.getVisibleMainCon=function(){var a=null;1==cuClickLxLe?a=$(".mainConInner:visible"):2==cuClickLxLe&&(a=$(".ejLxDiv:visible"));"qs"==cdDaType&&(a=$("body"));return a};b.getVisibleMainConHi=function(){var a=$("#jxDiv").height(),
c=$("#iHeader").height(),a=a?a:0,c=c?c:0;return b.getVisibleMainCon().height()+c+a};b.updateLxPageZdProp=function(a,c){if(mapLxPagePos&&0<mapLxPagePos.size()){var b=mapLxPagePos.get(cuPrHyUserViLxId);b&&(b[a]=c)}};b.isLxPageZdPropVal=function(a,c){if(mapLxPagePos&&0<mapLxPagePos.size()){var b=mapLxPagePos.get(cuPrHyUserViLxId);if(b)return b[a]==c}return!1};b.getRandomNum=function(a,c){var b=c-a,e=Math.random();return a+Math.round(e*b)};return b}(window.DmVideoGl||{}),videoWi=DmVideoGl.getVideoWi(),
videoHi=DmVideoGl.getVideoHi(),cdDaType=DmVideoGl.getCdDaType(),dzBoLoadHi=DmVideoGl.getDzBoLoadHi(),cuClickLxLe=1,ajaxViListJb=null,isSeAllByCuLx=!1,ajaxCkIsCanPlayJb=null,ajaxAddHyPlViReJb=null,isAddingPlViRecord=!1,cuPrHyUserViLxId=-1,bindReadyEventJb=null,groupArr=null,mapLoadUrls=new Map,mapLxPagePos=new Map,mapViCanPlay=new Map,mapViTimeUpdate=new Map,isPageLoading=!1,splitPageDqNumAjax=1,splitPageMyNumAjax=DmVideoGl.getSplitPageMyNumAjax(),splitPageZyNumAjax=0,splitPageZjNumAjax=0,DmVideoGlInp=
function(b){b.doMethodByHiInp=function(){b.bindClickZkqEditBtn();b.bindClickThumbHiInp();b.startLoadMyListViHiInp()};b.bindClickZkqEditBtn=function(){$(".edVideo").bind("click",function(a){a=$("#mainConDiv");var c=a.hasClass("editMod");a.removeClass("editMod");c||a.addClass("editMod")})};b.bindClickThumbHiInp=function(){var a=$(".thumb");a.unbind("click");a.bind("click",function(a){b.setPropsByClickLxAll($(this));a=1*$(this).attr("data-lx-id");var d=$(this).attr("id")+"Con";cuClickLxLe=1*$(this).attr("data-lx-level");
$(".mainConInner").hide();$("#"+d).show();$(".thumb").removeClass("active");$(this).addClass("active");$(".ejLxDiv").hide();$(".ejLxLinkCls").show();b.clickOtViLxCoreDeal(a)})};b.clickOtViLxCoreDeal=function(a){cuPrHyUserViLxId=a;ajaxViListJb&&ajaxViListJb.abort();ajaxCkIsCanPlayJb&&ajaxCkIsCanPlayJb.abort();ajaxAddHyPlViReJb&&ajaxAddHyPlViReJb.abort();var c=$.trim($(".ejLxDiv:visible").prev().prop("outerText")),c=$(".thumb.active").find("b").text()+(c?"->":"")+c,d=$(".ctrlDiv").find(".msTitle");
d.text(c);d.attr("title",c);b.setLxVerPropsHiInp(a);a=DmVideoGl.isLxPageZdPropVal("isClickAllSp",!0);b.isCuLxPageLoFiPageHiInp()&&a||b.startLoadMyListViHiInp()};b.setLxVerPropsHiInp=function(a){mapLxPagePos&&0<mapLxPagePos.size()&&(a=mapLxPagePos.get(a))&&(splitPageDqNumAjax=a.dqNum,splitPageZjNumAjax=a.zjNum,splitPageZyNumAjax=a.zyNum,splitPageMyNumAjax=splitPageMyNumAjax=a.myNum)};b.startLoadMyListViHiInp=function(){if(b.isCanSeMyViList("ckStartLoad")){var a=getActionByHz("action/hySe/prHyUserVi/seMyListVideosAjax?prHyUserViLx.id="+
cuPrHyUserViLxId+"&splitPageParameter.splitPageDqNumAjax="+splitPageDqNumAjax+"&isSeAllByCuLx="+isSeAllByCuLx);isPageLoading=!0;$(".loadMore").find("span").text("\u6b63\u5728\u62fc\u547d\u4e3a\u60a8\u8f7d\u5165...");ajaxViListJb=$.post(a,{},function(a){var d=a.listChildPrHyUserViLxs,e=d&&0<d.length;b.updatePropAfterAjaxHiInp(a);if(e){a=SideCls.crSinSecondLxArr(d);var d="",f=SideCls.getDefaultLxImage(null),g=cuPrHyUserViLxId+"All",d=d+('  <a id="ejLxLink'+g+'" data-lx-id="'+cuPrHyUserViLxId+'" data-lx-level="2" class="sinLink ejLxLinkCls ejLxLinkAllCls" href="javascript:;" target="_blank"><img src="'+
f+'" />\u8be5\u7c7b\u578b\u6240\u6709\u89c6\u9891</a>\n'),d=d+SideCls.appendThirdLxViDatas(g),d=d+SideCls.appendSecondLxDatas(a,"video");DmVideoGl.getVisibleMainCon().append(d);b.bindClickEjLxLink();b.bindClickSjLxLinkBk()}else b.startMethodByDataArrHiInp(a.listPrHyUserVis);splitPageDqNumAjax++;e?DmVideoGl.isLxPageZdPropVal("isClickAllSp",!0)&&DmVideoGl.updateLxPageZdProp("dqNum",splitPageDqNumAjax):DmVideoGl.updateLxPageZdProp("dqNum",splitPageDqNumAjax);isPageLoading=!1;$(".loadMore").find("span").text("")}).error(function(a){console.error(a);
isPageLoading=!1;$(".loadMore").find("span").text("")})}};b.bindClickEjLxLink=function(){var a=$(".ejLxLinkCls");a.unbind("click");a.bind("click",function(a){b.setPropsByClickLxAll($(this));a=$(this).attr("id")+"Con";$(".ejLxLinkCls").hide();$("#"+a).show();a=1*$(this).attr("data-lx-id");cuClickLxLe=1*$(this).attr("data-lx-level");b.clickOtViLxCoreDeal(a)})};b.bindClickSjLxLinkBk=function(){$(".sjLkBkVi").bind("click",function(a){$(".ejLxDiv").hide();$(".ejLxLinkCls").show()})};b.setPropsByClickLxAll=
function(a){isSeAllByCuLx=!1;a.hasClass("ejLxLinkAllCls")&&(isSeAllByCuLx=!0)};b.isCanSeMyViList=function(a){if(isPageLoading)return!1;if(mapLxPagePos&&0<mapLxPagePos.size()){var c=mapLxPagePos.get(cuPrHyUserViLxId);a=c.dqNum;var b=c.zyNum,c=c.prePage;if(isSeAllByCuLx){if(!DmVideoGl.isLxPageZdPropVal("isClickAllSp",!0)||c!=a&&(a<b||a==b))return!0}else if(null==c||c!=a&&(a<b||a==b))return!0}return!1};b.isCuLxPageLoFiPageHiInp=function(){return mapLxPagePos&&0<mapLxPagePos.size()&&null!=mapLxPagePos.get(cuPrHyUserViLxId).prePage?
!0:!1};b.updatePropAfterAjaxHiInp=function(a){var c=a.listChildPrHyUserViLxs,d=(c=c&&0<c.length)?isSeAllByCuLx?isSeAllByCuLx:!1:!0;splitPageDqNumAjax=a.splitPageDqNumAjax;splitPageZjNumAjax=a.splitPageZjNumAjax;splitPageZyNumAjax=a.splitPageZyNumAjax;splitPageMyNumAjax=a.splitPageMyNumAjax;b.updateDocYsStyles(c);b.updateLxPagePropsHiInp(splitPageDqNumAjax,splitPageMyNumAjax,splitPageZjNumAjax,splitPageZyNumAjax,splitPageDqNumAjax?splitPageDqNumAjax-1:0,d)};b.updateDocYsStyles=function(a){a?$(".mainConDiv").css("padding",
"0 .11rem"):$(".mainConDiv").css("padding","0")};b.updateLxPagePropsHiInp=function(a,c,b,e,f,g){if(mapLxPagePos&&0<mapLxPagePos.size()){var h=mapLxPagePos.get(cuPrHyUserViLxId),k=SideCls.crSinLxPageProp(a,c,b,e,f,g);console.info("\u5c06:cuPrHyUserViLxId:"+cuPrHyUserViLxId+"\u7684\u5c5e\u6027\u66f4\u65b0,\u60c5\u51b5\u662f:dqNum:"+h.dqNum+"->"+a+",myNum:"+h.myNum+"->"+c+",zjNum:"+h.zjNum+"->"+b+",zyNum:"+h.zyNum+"->"+e+",prePage:"+h.prePage+"->"+f+",isClickAllSp:"+h.isClickAllSp+"->"+g);mapLxPagePos.put(cuPrHyUserViLxId,
k)}};b.startMethodByDataArrHiInp=function(a){a&&0<a.length&&(groupArr=DmVideoGl.getSplitArrs(a,splitPageMyNumAjax),a=useViZsCls?useViZsCls:DmVideo,groupArr&&0<groupArr.length&&a.startClSinGroup(groupArr[0]))};b.ckIsCanPlay=function(a,c,b){a=getActionByHz("action/hySe/prHyUserVi/ckIsCanPlayAjax?id="+a);ajaxCkIsCanPlayJb=$.post(a,{},function(a){c&&c(a)}).error(function(a){b&&b(a)})};b.addHyPlayViRecord=function(a,c,b){var e=getActionByHz("action/hySe/prHyUserVi/addPlayViRecordAjax?id="+a);ajaxAddHyPlViReJb=
$.post(e,{},function(a){c&&c(a)}).error(function(c){b&&b(c,a)})};b.bindClickSinVideoEdit=function(a){a=$(a).find(".editBtn");$(a).bind("click",function(a){a=$(this).parent().attr("data-id");a=getActionByHz("action/hySe/prHyUserVi/toEdMyVideo?id="+a);location.href=a})};b.bindClickSinVideoDelete=function(a){a=$(a).find(".delBtn");$(a).bind("click",function(a){var b=$(this).parent().attr("data-id");layer.open({btn:["\u786e\u5b9a","\u53d6\u6d88"],content:"\u60a8\u786e\u5b9a\u8981\u5220\u9664\u8be5\u89c6\u9891\u5417\uff1f",
yes:function(a){var c=layer.open({type:2});a=getActionByHz("action/hySe/prHyUserVi/deleteUserViAjax");$.post(a,{id:b},function(a){layer.close(c);var b=a.prHyUserViId;showTipMsg(a.messageContent);$("#viEditDiv_"+b).parents(".mejs__container").remove()}).error(function(a){layer.close(c);showTipMsg("\u5220\u9664\u89c6\u9891\u5f02\u5e38:"+a)})}})})};return b}(window.DmVideoGlInp||{});