$(document).ready(function(){wrap_DmVideoVm()});function wrap_DmVideoVm(){DmVideoVm.startMethod()}
var DmVideoVm=function(c){c.startMethod=function(){"qs"==cdDaType?(DmVideoGl.bindScroll(function(){c.startClSinGroup(groupArr[splitPageDqNumAjax-1])}),c.startMethodByQs()):"inp"==cdDaType&&(DmVideoGl.bindScroll(function(){DmVideoGlInp.startLoadMyListViHiInp()}),DmVideoGlInp.doMethodByHiInp())};c.startMethodByQs=function(){var a=getQsArr().pa,a=a&&a.split("Hyu");c.startMethodByDataArr(a)};c.startMethodByDataArr=function(a){if(a&&0<a.length){var b=a.length;groupArr=DmVideoGl.getSplitArrs(a,splitPageMyNumAjax);
splitPageZjNumAjax=b;splitPageZyNumAjax=groupArr.length;groupArr&&0<groupArr.length&&c.startClSinGroup(groupArr[0])}};c.startClSinGroup=function(a){var b=a.length;if("qs"==cdDaType)for(var d=0;d<b;d++){var f=$.trim(a[d]);c.startClSinVideo(d,b,f)}else for(d=0;d<b;d++){var e=a[d],h=$.trim(e.id),g=$.trim(e.viMs),f=$.trim(e.viZzUrl),k=$.trim(e.viTitle),e=$.trim(e.imagePath);c.startClSinVideo(d,b,f,h,k,g,e)}};c.startClSinVideo=function(a,b,d,f,e,h,g,k){h=browser.platform.mobile;b=DmVideoGl.getCleanUrl(d);
e=Storage.getItem(b+"_poster");k=Storage.getItem(b+"_viHeight");b=videoWi?"width:"+videoWi:"width:"+(h?c.getMobileViWiSec():"320px")+";";h=videoHi?"height:"+videoHi:"height:"+(h?c.getMobileViHiSec(k):"492px")+";";k="";g=e?e:g;e="lx_"+(cuPrHyUserViLxId+"").replace("-","fu");a=e+"_video"+(a+splitPageMyNumAjax*(splitPageDqNumAjax-1));k=k+(' <video lx-id-sec="'+e+'" vi-id="'+f+'" id="'+a+'" style="'+b+h+'" class="" playsinline  loop controls>\n')+('  <source src="'+d+'" type="video/mp4" />\n');k+=" </video>\n";
DmVideoGl.getVisibleMainCon().append(k);f=$("#"+a);b=f.mediaelementplayer({poster:g,playText:"\u70b9\u51fb\u8fdb\u884c\u64ad\u653e",iceFullScreenMod:"wefs",pauseOtherPlayers:!1,success:function(a){var b=$(a).find("video").attr("vi-id"),d=$(a).find("video").attr("lx-id-sec"),c=$(a).parents(".mejs__container"),f=.4*c.width(),d="viEditDiv_"+d+"_"+b;c.append('<div class="viEditDiv" id="'+d+'" data-id="'+b+'"><input type="button" class="editBtn ctrlBtn" style="max-width:'+f+'px;" value="\u7f16\u8f91"><input type="button" class="delBtn ctrlBtn" style="max-width:'+
f+'px;" value="\u5220\u9664"></div>\n');c.addClass("viEditCon");DmVideoGlInp.bindClickSinVideoEdit($("#"+d));DmVideoGlInp.bindClickSinVideoDelete($("#"+d));a.addEventListener("loadeddata",function(a){},!1);a.addEventListener("play",function(a){var b=a.target,d=$(b).find("video");a=d.attr("vi-id");$(d).attr("autobuffer","autobuffer");if(a&&"undefined"!=a){var c=1*a,d=mapViCanPlay.get(c);(c=mapViTimeUpdate.get(c))&&c.stTime&&(c.stTime=new Date);void 0!=d?d.isSuccess||(b.pause(),alertVipLiSmPop("\u7acb\u5373\u5145\u503c",
d.msg)):DmVideoGlInp.ckIsCanPlay(a,function(a){var d=a.isSuccess;mapViCanPlay.put(a.prHyUserViId,{msg:a.messageContent,isSuccess:d});d||(b.pause(),"mustCz"==a.messageCode&&alertVipLiSmPop("\u7acb\u5373\u5145\u503c",a.messageContent))},function(){})}},!1);a.addEventListener("timeupdate",function(a){var b=$(a.target).find("video");a=1*b.attr("vi-id");b=b[0].currentTime;if(mapViTimeUpdate.get(a)){var d=mapViTimeUpdate.get(a),c=d.stPlTime;10<calcDateChaSeconds(d.stTime,new Date)&&b!=c&&!isAddingPlViRecord&&
!d.isRqAddedRecord&&(isAddingPlViRecord=!0,DmVideoGlInp.addHyPlayViRecord(a,function(a){isAddingPlViRecord=!1;var b=a.isSuccess,d=mapViTimeUpdate.get(a.prHyUserViId);d.isRqAddedRecord||(d.isRqAddedRecord=!0);b||console.error(a.messageContent)},function(a,b){isAddingPlViRecord=!1;var d=mapViTimeUpdate.get(b);d.isRqAddedRecord||(d.isRqAddedRecord=!0)}))}else mapViTimeUpdate.put(a,{stTime:new Date,stPlTime:b,isRqAddedRecord:!1})},!1)}});if(!g)if(browser.platform.mobile)if(browser.platform.iPhone)if(g=
mapLoadUrls.size(),e=mapLoadUrls.get(a),"qs"==cdDaType)16>g&&!e&&(b.load(),mapLoadUrls.put(a,d));else{if(cdDaType="inp",3>g&&!e)b.load(),mapLoadUrls.put(a,d)}else b.load(),mapLoadUrls.put(a,d);else b.load(),mapLoadUrls.put(a,d);return f};c.getMobileViWiSec=function(){if(browser.platform.mobile)return"100%"};c.getMobileViHiSec=function(a){if(browser.platform.mobile)return a?a:$(window).height()/3};c.bindReadyEvent=function(){if(browser.platform.mobile){var a=$("video").not(".loaded"),b=DmVideoGl.getRandomNum(0,
a.length-1),a=$(a[b]);(b=a[0].videoHeight)&&0<b&&(a.addClass("loaded"),c.dealCuPageVideoProps(a));0==$("video").not(".loaded").length?window.clearTimeout(bindReadyEventJb):bindReadyEventJb=setTimeout(c.bindReadyEvent,200)}};c.dealCuPageVideoProps=function(a){browser.platform.mobile&&(a=a[0],Storage.getItem(a.currentSrc+"_poster")||DmVideoGl.startDrawCvsImage(a,function(a,d){if(d){var c=d.src;c&&c.startWith("data:image/png")&&DmVideoGl.getCleanUrl(a.currentSrc)}}))};return c}(window.DmVideoVm||{}),
DmVideoGl=function(c){c.getVideoWi=function(){var a="",b=$("#pa_videoWi");b&&0<b.length&&(a=1*b.val());return a};c.getVideoHi=function(){var a="",b=$("#pa_videoHi");b&&0<b.length&&(a=1*b.val());return a};c.getCdDaType=function(){var a="qs",b=$("#pa_cdDaType");b&&0<b.length&&(a=b.val());return a};c.getDzBoLoadHi=function(){var a=0,b=$("#loadMore").height();b&&0<b.length&&(a=1*b.val());return a};c.getSplitPageMyNumAjax=function(){var a=0,a="qs"==c.getCdDaType()?16:browser.platform.mobile?5:12,b=$("#pa_splMyNum");
b&&0<b.length&&(a=1*b.val());return a};c.startDrawCvsImage=function(a,b){var d=document.createElement("canvas"),f=d.getContext("2d");d.width=a.videoWidth;d.height=a.videoHeight;a.crossOrigin="*";f.drawImage(a,0,0,d.width,d.height);f=c.getCanvasImage(d);c.dbScaleTarWiHi(d.width,d.height,$(a).width(),f);b&&b(a,f)};c.dbScaleTarWiHi=function(a,b,d,c){a>b?(c.width=d,c.height=d*b/a):(c.width=d*a/b,c.height=d)};c.getCanvasImage=function(a){var b=document.createElement("img");b.crossOrigin="*";b.src=a.toDataURL("image/png");
return b};c.captureCanvas=function(a,b){html2canvas(a,{onrendered:function(a){b&&b(a)}})};c.getSplitArrs=function(a,b){for(var d=0,d=0,c=1*b,e=[],d=a.length,d=Math.floor((d+c-1)/c),h=0;h<d;h++){for(var g=[],k=0;k<c&&0!=a.length;k++)g.push(a[0]),a.splice(0,1);e.push(g)}return e};c.getCleanUrl=function(a){var b="";return b=-1!=a.indexOf("?")?a.substring(0,a.indexOf("?")):a};c.bindScroll=function(a){$(window).scroll(function(){if(splitPageDqNumAjax>splitPageZyNumAjax)$(".loadMore").height(0);else if(DmVideoGlInp.isCanSeMyViList("ckScroll")){var b=
$(window).scrollTop(),d=$(window).height();c.getVisibleMainConHi()-b-d<=dzBoLoadHi&&a&&a()}})};c.getVisibleMainCon=function(){var a=null;1==cuClickLxLe?a=$(".mainConInner:visible"):2==cuClickLxLe&&(a=$(".ejLxDiv:visible"));"qs"==cdDaType&&(a=$("body"));return a};c.getVisibleMainConHi=function(){var a=$("#jxDiv").height(),b=$("#iHeader").height(),a=a?a:0,b=b?b:0;return c.getVisibleMainCon().height()+b+a};c.updateLxPageZdProp=function(a,b){if(mapLxPagePos&&0<mapLxPagePos.size()){var d=mapLxPagePos.get(cuPrHyUserViLxId);
d&&(d[a]=b)}};c.isLxPageZdPropVal=function(a,b){if(mapLxPagePos&&0<mapLxPagePos.size()){var d=mapLxPagePos.get(cuPrHyUserViLxId);if(d)return d[a]==b}return!1};c.getRandomNum=function(a,b){var d=b-a,c=Math.random();return a+Math.round(c*d)};return c}(window.DmVideoGl||{}),videoWi=DmVideoGl.getVideoWi(),videoHi=DmVideoGl.getVideoHi(),cdDaType=DmVideoGl.getCdDaType(),dzBoLoadHi=DmVideoGl.getDzBoLoadHi(),cuClickLxLe=1,ajaxViListJb=null,isSeAllByCuLx=!1,ajaxCkIsCanPlayJb=null,ajaxAddHyPlViReJb=null,isAddingPlViRecord=
!1,cuPrHyUserViLxId=-1,bindReadyEventJb=null,groupArr=null,mapLoadUrls=new Map,mapLxPagePos=new Map,mapViCanPlay=new Map,mapViTimeUpdate=new Map,isPageLoading=!1,splitPageDqNumAjax=1,splitPageMyNumAjax=DmVideoGl.getSplitPageMyNumAjax(),splitPageZyNumAjax=0,splitPageZjNumAjax=0,DmVideoGlInp=function(c){c.doMethodByHiInp=function(){c.bindClickZkqEditBtn();c.bindClickThumbHiInp();c.startLoadMyListViHiInp()};c.bindClickZkqEditBtn=function(){$(".edVideo").bind("click",function(a){a=$("#mainConDiv");var b=
a.hasClass("editMod");a.removeClass("editMod");b||a.addClass("editMod")})};c.bindClickThumbHiInp=function(){var a=$(".thumb");a.unbind("click");a.bind("click",function(a){c.setPropsByClickLxAll($(this));a=1*$(this).attr("data-lx-id");var d=$(this).attr("id")+"Con";cuClickLxLe=1*$(this).attr("data-lx-level");$(".mainConInner").hide();$("#"+d).show();$(".thumb").removeClass("active");$(this).addClass("active");$(".ejLxDiv").hide();$(".ejLxLinkCls").show();c.clickOtViLxCoreDeal(a)})};c.clickOtViLxCoreDeal=
function(a){cuPrHyUserViLxId=a;ajaxViListJb&&ajaxViListJb.abort();ajaxCkIsCanPlayJb&&ajaxCkIsCanPlayJb.abort();ajaxAddHyPlViReJb&&ajaxAddHyPlViReJb.abort();var b=$.trim($(".ejLxDiv:visible").prev().prop("outerText")),b=$(".thumb.active").find("b").text()+(b?"->":"")+b,d=$(".ctrlDiv").find(".msTitle");d.text(b);d.attr("title",b);c.setLxVerPropsHiInp(a);a=DmVideoGl.isLxPageZdPropVal("isClickAllSp",!0);c.isCuLxPageLoFiPageHiInp()&&a||c.startLoadMyListViHiInp()};c.setLxVerPropsHiInp=function(a){mapLxPagePos&&
0<mapLxPagePos.size()&&(a=mapLxPagePos.get(a))&&(splitPageDqNumAjax=a.dqNum,splitPageZjNumAjax=a.zjNum,splitPageZyNumAjax=a.zyNum,splitPageMyNumAjax=splitPageMyNumAjax=a.myNum)};c.startLoadMyListViHiInp=function(){if(c.isCanSeMyViList("ckStartLoad")){var a=getActionByHz("action/hySe/prHyUserVi/seMyListVideosAjax?prHyUserViLx.id="+cuPrHyUserViLxId+"&splitPageParameter.splitPageDqNumAjax="+splitPageDqNumAjax+"&isSeAllByCuLx="+isSeAllByCuLx);isPageLoading=!0;$(".loadMore").find("span").text("\u6b63\u5728\u62fc\u547d\u4e3a\u60a8\u8f7d\u5165...");
ajaxViListJb=$.post(a,{},function(a){var d=a.listChildPrHyUserViLxs,f=d&&0<d.length;c.updatePropAfterAjaxHiInp(a);if(f){a=SideCls.crSinSecondLxArr(d);var d="",e=SideCls.getDefaultLxImage(null),h=cuPrHyUserViLxId+"All",d=d+('  <a id="ejLxLink'+h+'" data-lx-id="'+cuPrHyUserViLxId+'" data-lx-level="2" class="sinLink ejLxLinkCls ejLxLinkAllCls" href="javascript:;" target="_blank"><img src="'+e+'" />\u8be5\u7c7b\u578b\u6240\u6709\u89c6\u9891</a>\n'),d=d+SideCls.appendThirdLxViDatas(h),d=d+SideCls.appendSecondLxDatas(a,
"video");DmVideoGl.getVisibleMainCon().append(d);c.bindClickEjLxLink();c.bindClickSjLxLinkBk()}else c.startMethodByDataArrHiInp(a.listPrHyUserVis);splitPageDqNumAjax++;f?DmVideoGl.isLxPageZdPropVal("isClickAllSp",!0)&&DmVideoGl.updateLxPageZdProp("dqNum",splitPageDqNumAjax):DmVideoGl.updateLxPageZdProp("dqNum",splitPageDqNumAjax);isPageLoading=!1;$(".loadMore").find("span").text("")}).error(function(a){console.error(a);isPageLoading=!1;$(".loadMore").find("span").text("")})}};c.bindClickEjLxLink=
function(){var a=$(".ejLxLinkCls");a.unbind("click");a.bind("click",function(a){c.setPropsByClickLxAll($(this));a=$(this).attr("id")+"Con";$(".ejLxLinkCls").hide();$("#"+a).show();a=1*$(this).attr("data-lx-id");cuClickLxLe=1*$(this).attr("data-lx-level");c.clickOtViLxCoreDeal(a)})};c.bindClickSjLxLinkBk=function(){$(".sjLkBkVi").bind("click",function(a){$(".ejLxDiv").hide();$(".ejLxLinkCls").show()})};c.setPropsByClickLxAll=function(a){isSeAllByCuLx=!1;a.hasClass("ejLxLinkAllCls")&&(isSeAllByCuLx=
!0)};c.isCanSeMyViList=function(a){if(isPageLoading)return!1;if(mapLxPagePos&&0<mapLxPagePos.size()){var b=mapLxPagePos.get(cuPrHyUserViLxId);a=b.dqNum;var d=b.zyNum,b=b.prePage;if(isSeAllByCuLx){if(!DmVideoGl.isLxPageZdPropVal("isClickAllSp",!0)||b!=a&&(a<d||a==d))return!0}else if(null==b||b!=a&&(a<d||a==d))return!0}return!1};c.isCuLxPageLoFiPageHiInp=function(){return mapLxPagePos&&0<mapLxPagePos.size()&&null!=mapLxPagePos.get(cuPrHyUserViLxId).prePage?!0:!1};c.updatePropAfterAjaxHiInp=function(a){var b=
a.listChildPrHyUserViLxs,d=(b=b&&0<b.length)?isSeAllByCuLx?isSeAllByCuLx:!1:!0;splitPageDqNumAjax=a.splitPageDqNumAjax;splitPageZjNumAjax=a.splitPageZjNumAjax;splitPageZyNumAjax=a.splitPageZyNumAjax;splitPageMyNumAjax=a.splitPageMyNumAjax;c.updateDocYsStyles(b);c.updateLxPagePropsHiInp(splitPageDqNumAjax,splitPageMyNumAjax,splitPageZjNumAjax,splitPageZyNumAjax,splitPageDqNumAjax?splitPageDqNumAjax-1:0,d)};c.updateDocYsStyles=function(a){a?$(".mainConDiv").css("padding","0 .11rem"):$(".mainConDiv").css("padding",
"0")};c.updateLxPagePropsHiInp=function(a,b,d,c,e,h){if(mapLxPagePos&&0<mapLxPagePos.size()){var g=mapLxPagePos.get(cuPrHyUserViLxId),k=SideCls.crSinLxPageProp(a,b,d,c,e,h);console.info("\u5c06:cuPrHyUserViLxId:"+cuPrHyUserViLxId+"\u7684\u5c5e\u6027\u66f4\u65b0,\u60c5\u51b5\u662f:dqNum:"+g.dqNum+"->"+a+",myNum:"+g.myNum+"->"+b+",zjNum:"+g.zjNum+"->"+d+",zyNum:"+g.zyNum+"->"+c+",prePage:"+g.prePage+"->"+e+",isClickAllSp:"+g.isClickAllSp+"->"+h);mapLxPagePos.put(cuPrHyUserViLxId,k)}};c.startMethodByDataArrHiInp=
function(a){a&&0<a.length&&(groupArr=DmVideoGl.getSplitArrs(a,splitPageMyNumAjax),a=useViZsCls?useViZsCls:DmVideo,groupArr&&0<groupArr.length&&a.startClSinGroup(groupArr[0]))};c.ckIsCanPlay=function(a,b,c){a=getActionByHz("action/hySe/prHyUserVi/ckIsCanPlayAjax?id="+a);ajaxCkIsCanPlayJb=$.post(a,{},function(a){b&&b(a)}).error(function(a){c&&c(a)})};c.addHyPlayViRecord=function(a,b,c){var f=getActionByHz("action/hySe/prHyUserVi/addPlayViRecordAjax?id="+a);ajaxAddHyPlViReJb=$.post(f,{},function(a){b&&
b(a)}).error(function(b){c&&c(b,a)})};c.bindClickSinVideoEdit=function(a){a=$(a).find(".editBtn");$(a).bind("click",function(a){a=$(this).parent().attr("data-id");a=getActionByHz("action/hySe/prHyUserVi/toEdMyVideo?id="+a);location.href=a})};c.bindClickSinVideoDelete=function(a){a=$(a).find(".delBtn");$(a).bind("click",function(a){var c=$(this).parent().attr("data-id");layer.open({btn:["\u786e\u5b9a","\u53d6\u6d88"],content:"\u60a8\u786e\u5b9a\u8981\u5220\u9664\u8be5\u89c6\u9891\u5417\uff1f",yes:function(a){var b=
layer.open({type:2});a=getActionByHz("action/hySe/prHyUserVi/deleteUserViAjax");$.post(a,{id:c},function(a){layer.close(b);var c=a.prHyUserViId;showTipMsg(a.messageContent);$("#viEditDiv_"+c).parents(".mejs__container").remove()}).error(function(a){layer.close(b);showTipMsg("\u5220\u9664\u89c6\u9891\u5f02\u5e38:"+a)})}})})};return c}(window.DmVideoGlInp||{});